// Import the 'fs' module for file system operations
const fs = require('fs');
// Import the 'path' module for working with file paths
const path = require('path');
// Import the 'uuid' module for generating a unique ID
const uuid = require('../helpers/uuid');
// Import the 'Router' class from the 'express' module for defining routes
const router = require('express').Router();
// Import the 'readFromFile' and 'readAndAppend' functions from '../helpers/fsUtils'
const { readFromFile, readAndAppend } = require('../helpers/fsUtils');


// Route to handle retrieving all notes
router.get('/api/notes', (req, res) => {
  console.info(`${req.method} request received for notes`);
  // Read the contents of 'db.json' file and send it as a response
  readFromFile('./db/db.json').then((data) => res.json(JSON.parse(data)));
});

// Route to handle saving a new note
router.post('/api/notes', (req, res) => {
  console.info(`${req.method} request received to add a note`);
  console.log(req.body);

  // Extract the 'title' and 'text' from the request body
  const { title, text } = req.body;

  if (req.body) {
    // Create a new note object with a unique 'id' generated by 'uuid' module
    const newNote = {
      title,
      text,
      id: uuid(),
    };
    // Append the new note to 'db.json' file
    readAndAppend(newNote, './db/db.json');
    // Send a success response
    res.json(`Note added successfully 🚀`);
  } else {
    // Send an error response
    res.error('Error in adding the new note.');
  }
});

// Route to handle deleting a note
router.delete('/api/notes/:id', (req, res) => {
  // Read the contents of 'db.json' file
  const data = fs.readFileSync('db/db.json', 'utf8');
  const dataJson = JSON.parse(data);
  // Filter out the note with the provided 'id'
  const newNotes = dataJson.filter((note) => {
    return note.id !== req.params.id;
  });
  // Write the updated notes to 'db.json' file
  fs.writeFileSync('db/db.json', JSON.stringify(newNotes));
  
  // Send a success message as a JSON response
  console.info(`${req.method} Note deleted successfully.`);
  res.status(200).json({ message: 'Note deleted successfully.' });
});

// Export the router to be used in other modules
module.exports = router;